INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL,'Engineering');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL,'IT Support');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL,'Finance');
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL,'Human Resources');


INSERT INTO EMPLOYEE
(EMP_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, JOIN_DATE, DEPT_ID, CREATED_DATE, CREATED_BY, UPDATED_DATE, UPDATED_BY)
VALUES(EMPLOYEE_SEQ.NEXTVAL, 'John', 'Smith', '1980-07-14', '2010-02-18', 10, '2010-02-18 09:10:00', '123', '2010-02-18 09:10:00', '123');

INSERT INTO EMPLOYEE
(EMP_ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME,  DATE_OF_BIRTH, JOIN_DATE, DEPT_ID, CREATED_DATE, CREATED_BY, UPDATED_DATE, UPDATED_BY)
VALUES(EMPLOYEE_SEQ.NEXTVAL, 'Rachel', 'J', 'Thompson', '1990-05-31', '2012-09-23', 20, '2012-09-23 10:00:18', '234', '2012-09-23 10:00:18', '234');

INSERT INTO EMPLOYEE
(EMP_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, JOIN_DATE, DEPT_ID, CREATED_DATE, CREATED_BY, UPDATED_DATE, UPDATED_BY)
VALUES(EMPLOYEE_SEQ.NEXTVAL, 'William', 'Baiely', '1982-04-27', '2007-02-18', 30, '2007-02-18 09:10:00', '123', '2007-02-18 09:10:00', '123');

INSERT INTO EMPLOYEE
(EMP_ID, FIRST_NAME, MIDDLE_INITIAL, LAST_NAME,  DATE_OF_BIRTH, JOIN_DATE, DEPT_ID, CREATED_DATE, CREATED_BY, UPDATED_DATE, UPDATED_BY)
VALUES(EMPLOYEE_SEQ.NEXTVAL, 'Robert', 'K', 'Joseph', '1975-11-19', '2003-09-23',40, '2003-09-23 10:00:18', '234', '2003-09-23 10:00:18', '234');

INSERT INTO EMPLOYEE
(EMP_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, JOIN_DATE, DEPT_ID, CREATED_DATE, CREATED_BY, UPDATED_DATE, UPDATED_BY)
VALUES(EMPLOYEE_SEQ.NEXTVAL, 'Brian', 'Worst', '1992-05-05', '2015-02-18', 10, '2015-02-18 09:10:00', '123', '2015-02-18 09:10:00', '123');



INSERT INTO CONTACT (CONTACT_ID, EMAIL, EMP_ID) VALUES  (CONTACT_SEQ.NEXTVAL, 'john.smith@fauxComp.com', 1);
INSERT INTO CONTACT (CONTACT_ID, EMP_ID) VALUES (CONTACT_SEQ.NEXTVAL, 2);
INSERT INTO CONTACT (CONTACT_ID, EMAIL, EMP_ID) VALUES  (CONTACT_SEQ.NEXTVAL, 'william.baiely@fauxComp.com', 3);
INSERT INTO CONTACT (CONTACT_ID, EMAIL, EMP_ID) VALUES  (CONTACT_SEQ.NEXTVAL, 'robert.joseph@fauxComp.com', 4);
INSERT INTO CONTACT (CONTACT_ID, EMAIL, EMP_ID) VALUES (CONTACT_SEQ.NEXTVAL, 'brian.worst@fauxComp.com', 5);



INSERT INTO ADDRESS (ADDRESS_ID, STREET1, STREET2, CITY, STATE, ZIP_CODE, CONTACT_ID, ADDR_TYPE) VALUES(ADDRESS_SEQ.NEXTVAL, '1 test st.', '401', 'Ellicott City', 'MD', '20142', 5, 'Home');
INSERT INTO ADDRESS (ADDRESS_ID, STREET1, CITY, STATE, ZIP_CODE, CONTACT_ID, ADDR_TYPE) VALUES(ADDRESS_SEQ.NEXTVAL, '25 NW st.', 'Baltimore', 'MD', '21202', 5, 'Work');

INSERT INTO ADDRESS (ADDRESS_ID, STREET1, STREET2, CITY, STATE, ZIP_CODE, CONTACT_ID, ADDR_TYPE) VALUES(ADDRESS_SEQ.NEXTVAL, '6 test St.', '205', 'Columbia', 'MD', '21045', 1, 'Home');

INSERT INTO ADDRESS (ADDRESS_ID, STREET1, CITY, STATE, ZIP_CODE, CONTACT_ID, ADDR_TYPE) VALUES(ADDRESS_SEQ.NEXTVAL, '2023 south St.', 'Laurel', 'MD', '21072', 2, 'Home');

INSERT INTO ADDRESS (ADDRESS_ID, STREET1, CITY, STATE, ZIP_CODE, CONTACT_ID, ADDR_TYPE)VALUES(ADDRESS_SEQ.NEXTVAL, '5906 North St.', 'Columbia', 'MD', '21075', 3, 'Home');

INSERT INTO ADDRESS (ADDRESS_ID, STREET1, STREET2, CITY, STATE, ZIP_CODE, CONTACT_ID, ADDR_TYPE) VALUES(ADDRESS_SEQ.NEXTVAL, '64 East St.', '103', 'Jessup', 'MD', '21022', 4, 'Home');
INSERT INTO ADDRESS (ADDRESS_ID, STREET1, CITY, STATE, ZIP_CODE, CONTACT_ID, ADDR_TYPE) VALUES(ADDRESS_SEQ.NEXTVAL, '791 Wall St.', 'Jessup', 'MD', '21022', 4, 'Mailing');



INSERT INTO PHONE (PHONE_ID, PHONE_NO, PHONE_TYPE, CONTACT_ID) VALUES(PHONE_SEQ.NEXTVAL, 1234567890, 'Cell', 1);
INSERT INTO PHONE (PHONE_ID, PHONE_NO, PHONE_TYPE, CONTACT_ID) VALUES(PHONE_SEQ.NEXTVAL, 9087654321, 'Home', 1);

INSERT INTO PHONE (PHONE_ID, PHONE_NO, PHONE_TYPE, CONTACT_ID) VALUES(PHONE_SEQ.NEXTVAL, 6789054321, 'Cell', 2);

INSERT INTO PHONE (PHONE_ID, PHONE_NO, PHONE_TYPE, CONTACT_ID) VALUES(PHONE_SEQ.NEXTVAL, 5432167890, 'Home', 3);

INSERT INTO PHONE (PHONE_ID, PHONE_NO, PHONE_TYPE, CONTACT_ID) VALUES(PHONE_SEQ.NEXTVAL, 1234509876, 'Work', 4);

INSERT INTO PHONE (PHONE_ID, PHONE_NO, PHONE_TYPE, CONTACT_ID) VALUES(PHONE_SEQ.NEXTVAL, 456782190, 'Cell', 5);
INSERT INTO PHONE (PHONE_ID, PHONE_NO, PHONE_TYPE, CONTACT_ID) VALUES(PHONE_SEQ.NEXTVAL, 8765439021, 'Work', 5);

INSERT INTO PROJECTS (PRJ_ID, "PRJ_NAME",EXPECTED_START_DATE,ACTUAL_START_DATE,EXPECTED_FINISH_DATE,ACTUAL_FINISH_DATE,CREATED_DATE,CREATED_BY,UPDATED_DATE,UPDATED_BY) VALUES
(PROJECT_SEQ.NEXTVAL,'First Project','2020-09-01',NULL,'2021-03-25',NULL,'2020-08-16 19:30:23.781','ADSF','2020-08-16 19:30:23.782','ADSF');

INSERT INTO EMP_PRJ (EMP_ID,PRJ_ID) VALUES (1,1),(5,1);

COMMIT;